### ISSUE TITLE
If user ID higher than 18 symbols, users cannot connect to server

### ISSUE THREAD

**Issue by MVAGamer** [MrQuackDuck/DiscordVerificator#1]
I installed this plugin on my server and I had a problem with some users. Plugin doesnt support User ID's higher than 18 symbols. Can u fix this problem in new versions?

**Comment by MrQuackDuck** [comment]
Thank you for reporting! I'll fix that

**Comment by MrQuackDuck** [comment]
Solved! Check out the new version ❤
